# Generated by Django 6.0.3 on 2026-03-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biotools", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="biotoolsrecord",
            name="edam_topic_uris",
            field=models.JSONField(
                default=list,
                help_text="List of EDAM topic URIs from bio.tools, e.g. ['http://edamontology.org/topic_0091'].",
            ),
        ),
        migrations.AlterField(
            model_name="biotoolsrecord",
            name="sync_error",
            field=models.TextField(
                blank=True,
                help_text="Last sync error message, if any. Empty when last sync succeeded.",
            ),
        ),
    ]
