# Generated by Django 6.0.3 on 2026-03-16 11:55

import apps.submissions.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("edam", "0002_add_indexes_and_elixir_year_fields"),
        ("registry", "0002_add_indexes_and_elixir_year_fields"),
        ("submissions", "0003_split_submitter_name"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="servicesubmission",
            new_name="submissions_status_64d2e8_idx",
            old_name="submission_status_idx",
        ),
        migrations.RenameIndex(
            model_name="servicesubmission",
            new_name="submissions_submitt_def5be_idx",
            old_name="submission_submitted_at_idx",
        ),
        migrations.RenameIndex(
            model_name="servicesubmission",
            new_name="submissions_service_ef8b7e_idx",
            old_name="submission_service_center_idx",
        ),
        migrations.AlterField(
            model_name="servicesubmission",
            name="associated_partner_note",
            field=models.TextField(
                blank=True,
                help_text="Required if 'Associated partner' is selected as a responsible PI. Provide full name and affiliation.",
            ),
        ),
        migrations.AlterField(
            model_name="servicesubmission",
            name="biotools_url",
            field=models.URLField(
                blank=True,
                help_text="Link to bio.tools entry (optional).",
                max_length=2000,
                validators=[
                    apps.submissions.models._validate_https_url,
                    apps.submissions.models._validate_biotools_url,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="servicesubmission",
            name="comments",
            field=models.TextField(
                blank=True,
                help_text="Any additional comments for the de.NBI administration office.",
            ),
        ),
        migrations.AlterField(
            model_name="servicesubmission",
            name="data_protection_consent",
            field=models.BooleanField(
                default=False,
                help_text="Consent to data protection information and privacy policy.",
            ),
        ),
        migrations.AlterField(
            model_name="servicesubmission",
            name="date_of_entry",
            field=models.DateField(help_text="Date this form was filled in."),
        ),
        migrations.AlterField(
            model_name="servicesubmission",
            name="edam_operations",
            field=models.ManyToManyField(
                blank=True,
                help_text="EDAM Operation terms describing what this service does (e.g. Sequence alignment, Visualisation). Select up to 6.",
                limit_choices_to={"branch": "operation", "is_obsolete": False},
                related_name="submissions_by_operation",
                to="edam.edamterm",
            ),
        ),
        migrations.AlterField(
            model_name="servicesubmission",
            name="edam_topics",
            field=models.ManyToManyField(
                blank=True,
                help_text="EDAM Topic terms describing the scientific domain of this service (e.g. Proteomics, Genomics). Select up to 6.",
                limit_choices_to={"branch": "topic", "is_obsolete": False},
                related_name="submissions_by_topic",
                to="edam.edamterm",
            ),
        ),
        migrations.AlterField(
            model_name="servicesubmission",
            name="fairsharing_url",
            field=models.URLField(
                blank=True,
                help_text="Link to FAIRsharing.org entry (optional).",
                max_length=2000,
                validators=[
                    apps.submissions.models._validate_https_url,
                    apps.submissions.models._validate_fairsharing_url,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="servicesubmission",
            name="github_url",
            field=models.URLField(
                blank=True,
                help_text="Link to GitHub repository (optional; must be https://github.com/...).",
                max_length=2000,
                validators=[
                    apps.submissions.models._validate_https_url,
                    apps.submissions.models._validate_github_url,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="servicesubmission",
            name="host_institute",
            field=models.CharField(
                help_text="The institute hosting this service.", max_length=300
            ),
        ),
        migrations.AlterField(
            model_name="servicesubmission",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Unique identifier for this submission (UUID).",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="servicesubmission",
            name="internal_contact_email",
            field=models.EmailField(
                help_text="Email address of the internal contact for administration office use. This address is NEVER publicly visible.",
                max_length=254,
            ),
        ),
        migrations.AlterField(
            model_name="servicesubmission",
            name="internal_contact_name",
            field=models.CharField(
                help_text="Name and affiliation of the internal contact person (admin use only).",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="servicesubmission",
            name="is_toolbox",
            field=models.BooleanField(
                default=False,
                help_text="True if this service is a toolbox of consolidated services or part of one.",
            ),
        ),
        migrations.AlterField(
            model_name="servicesubmission",
            name="keywords_seo",
            field=models.TextField(
                blank=True,
                help_text="Keywords for search engine optimisation of the service's listing page.",
            ),
        ),
        migrations.AlterField(
            model_name="servicesubmission",
            name="keywords_uncited",
            field=models.TextField(
                blank=True,
                help_text="Search keywords to identify usage without formal citation (e.g. tool name mentioned in methods but not in bibliography).",
            ),
        ),
        migrations.AlterField(
            model_name="servicesubmission",
            name="kpi_monitoring",
            field=models.CharField(
                choices=[("yes", "Yes"), ("planned", "Planned")],
                help_text="Whether KPI monitoring is currently in place or planned.",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="servicesubmission",
            name="kpi_start_year",
            field=models.CharField(
                help_text="Year KPI monitoring started, or estimated start year if planned. Use YYYY format or a short description.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="servicesubmission",
            name="license",
            field=models.CharField(
                choices=[
                    ("agpl3", "GNU AGPLv3"),
                    ("gpl3", "GNU GPLv3"),
                    ("lgpl3", "GNU LGPLv3"),
                    ("mpl2", "Mozilla Public License 2.0"),
                    ("apache2", "Apache License 2.0"),
                    ("mit", "MIT License"),
                    ("boost", "Boost Software License 1.0"),
                    ("unlicense", "The Unlicense"),
                    ("other", "None of the above"),
                    ("na", "Not applicable"),
                ],
                help_text="License governing use of this service.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="servicesubmission",
            name="other_registry_url",
            field=models.URLField(
                blank=True,
                help_text="Link to any other registry entry (optional).",
                max_length=2000,
                validators=[apps.submissions.models._validate_https_url],
            ),
        ),
        migrations.AlterField(
            model_name="servicesubmission",
            name="outreach_consent",
            field=models.BooleanField(
                default=False,
                help_text="Consent for de.NBI to showcase this service on social media.",
            ),
        ),
        migrations.AlterField(
            model_name="servicesubmission",
            name="public_contact_email",
            field=models.EmailField(
                help_text="Contact email displayed publicly on the de.NBI services page. This address is publicly visible.",
                max_length=254,
            ),
        ),
        migrations.AlterField(
            model_name="servicesubmission",
            name="publications_pmids",
            field=models.TextField(
                help_text="Comma-separated list of PMIDs or DOIs for publications connected to this service. PMIDs are required for ELIXIR impact assessment.",
                validators=[apps.submissions.models._validate_publications],
            ),
        ),
        migrations.AlterField(
            model_name="servicesubmission",
            name="register_as_elixir",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Whether to also register this service as an ELIXIR-DE service.",
            ),
        ),
        migrations.AlterField(
            model_name="servicesubmission",
            name="service_center",
            field=models.ForeignKey(
                help_text="Associated de.NBI service centre.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="submissions",
                to="registry.servicecenter",
            ),
        ),
        migrations.AlterField(
            model_name="servicesubmission",
            name="service_description",
            field=models.TextField(
                help_text="Description of the service, including technology used (e.g. AI/ML, programming language, data types handled)."
            ),
        ),
        migrations.AlterField(
            model_name="servicesubmission",
            name="service_name",
            field=models.CharField(
                help_text="Official name of the service.", max_length=300
            ),
        ),
        migrations.AlterField(
            model_name="servicesubmission",
            name="submitter_affiliation",
            field=models.CharField(
                default="",
                help_text="Institute or organisation affiliation of the person filling in this form.",
                max_length=300,
            ),
        ),
        migrations.AlterField(
            model_name="servicesubmission",
            name="submitter_first_name",
            field=models.CharField(
                default="",
                help_text="First name of the person filling in this form.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="servicesubmission",
            name="submitter_last_name",
            field=models.CharField(
                default="",
                help_text="Last name (surname) of the person filling in this form.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="servicesubmission",
            name="survey_participation",
            field=models.BooleanField(
                default=True,
                help_text="Willingness to participate in de.NBI user surveys.",
            ),
        ),
        migrations.AlterField(
            model_name="servicesubmission",
            name="terms_of_use_url",
            field=models.URLField(
                help_text="URL to the service's terms of use (must use https://).",
                max_length=2000,
                validators=[apps.submissions.models._validate_https_url],
            ),
        ),
        migrations.AlterField(
            model_name="servicesubmission",
            name="toolbox_name",
            field=models.CharField(
                blank=True,
                help_text="Name of the toolbox (required if is_toolbox is True).",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="servicesubmission",
            name="user_knowledge_required",
            field=models.TextField(
                blank=True,
                help_text="Any prerequisites for users to install, run, or use this service.",
            ),
        ),
        migrations.AlterField(
            model_name="servicesubmission",
            name="website_url",
            field=models.URLField(
                help_text="Public website URL of the service (must use https://).",
                max_length=2000,
                validators=[apps.submissions.models._validate_https_url],
            ),
        ),
        migrations.AlterField(
            model_name="servicesubmission",
            name="year_established",
            field=models.IntegerField(
                db_index=True,
                help_text="Year the service was first established (YYYY).",
            ),
        ),
        migrations.AlterField(
            model_name="submissionapikey",
            name="created_by",
            field=models.CharField(
                default="submitter",
                help_text="'submitter' for keys issued on form submission, or admin username.",
                max_length=150,
            ),
        ),
        migrations.AlterField(
            model_name="submissionapikey",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Set False to revoke this key. Revoked keys are retained for audit purposes and cannot be re-activated.",
            ),
        ),
        migrations.AlterField(
            model_name="submissionapikey",
            name="key_hash",
            field=models.CharField(
                db_index=True,
                editable=False,
                help_text="SHA-256 hash of the plaintext API key. The plaintext is never stored.",
                max_length=64,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="submissionapikey",
            name="label",
            field=models.CharField(
                default="Initial key",
                help_text="Human-readable label describing why this key was issued.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="submissionapikey",
            name="last_used_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp of the most recent successful authentication with this key.",
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="servicesubmission",
            index=models.Index(
                fields=["-submitted_at", "status"],
                name="submissions_submitt_fb9468_idx",
            ),
        ),
    ]
