# Generated by Django 6.0.3 on 2026-03-16 11:55

import apps.registry.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="principalinvestigator",
            name="orcid",
            field=models.CharField(
                blank=True,
                help_text="ORCID iD in format 0000-0000-0000-0000.",
                max_length=30,
                validators=[apps.registry.models._validate_orcid],
            ),
        ),
    ]
