# Generated by Django 6.0.3 on 2026-03-16 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edam', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='edamterm',
            new_name='edam_edamte_branch_be09d8_idx',
            old_name='edam_term_branch_obsolete_idx',
        ),
        migrations.RenameIndex(
            model_name='edamterm',
            new_name='edam_edamte_label_b1f629_idx',
            old_name='edam_term_label_idx',
        ),
    ]
